version: "1.0"
services:
   redis:
     image: redis
     container_name: redis-tc
     restart: always
     ports:
       - "6379:6379"
     command: redis-server
     volumes:
       - redis_data_tc:/data
     stdin_open: true
     tty: true

   mongo:
     image: mongo
     container_name: mongo-tc
     restart: always
     ports:
       - "27017:27017"
     volumes:
       - mongo_data_tc:/data
     stdin_open: true
     tty: true
   
   zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper-tc
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data_tc:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

   kafka:
    image: bitnami/kafka
    container_name: kafka-tc
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data_tc:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper

   kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: peaceful_wright
    ports:
      - "8080:8080"
    volumes:
      - "kafka_data_ui:/kafka-ui"
    restart: unless-stopped
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    
volumes:
  redis_data_tc:
    driver: local
  mongo_data_tc:
    driver: local
  zookeeper_data_tc:
    driver: local
  kafka_data_tc:
    driver: local
  kafka_data_view:
    driver: local
