version: '3.8'
services:
  agent:
    image: hosseinkhodabandeh/agent-service:latest
    container_name: agent_service
    ports:
      - "3000:3000"
    environment:
      AGENT_ID: 1
      KAFKA_TOPIC: main-topic
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: agent-client
      KAFKA_GROUP_ID: kafka-group
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
